export const products = [{ 
  mod: "glass",
  id: "sayed-2649438452",
  img: "./image/prodcts/men/men-round-eyeglasses-1.jpg",
  name: "Round EyeGlasses black men`s",
  lens: "Anti-Reflective",
  price: "1500",
  sale: "33",
  type: "men",
},{ 
  mod: "glass",
  id: "sayed-452873433423",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-2.jpg",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "2500",
  sale: "30",
  type: "sun",
},{ 
  mod: "glass",
  id: "sayed-4537438773484",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-3.jpg",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "1750",
  sale: "20",
  type: "sun",
},{ 
  mod: "glass",
  id: "sayed-2194743435863",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-1.png",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "1500",
  sale: "25",
  type: "sun",
},{ 
  mod: "glass",
  id: "sayed-21974347343463",
  img: "./image/prodcts/children/chil-round-eyeglasses-2.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  mod: "glass",
  id: "sayed-2194473435363",
  img: "./image/prodcts/children/chil-round-eyeglasses-3.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  mod: "glass",
  id: "sayed-4733478383",
  img: "./image/prodcts/children/chil-round-eyeglasses-1.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  mod: "glass",
  id: "sayed-47337435483",
  img: "./image/prodcts/women/women-round-eyeglasses-1.png",
  name: "EyeGlasses for women`s",
  lens: "Single Vision Lenses",
  price: "20000",
  sale: "20",
  type: "women",
},{ 
  mod: "glass",
  id: "sayed-473584738",
  img: "./image/prodcts/women/women-round-eyeglasses-3.png",
  name: "EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2000",
  sale: "30",
  type: "women",
},{ 
  mod: "glass",
  id: "sayed-473583743",
  img: "./image/prodcts/women/women-round-eyeglasses-2.png",
  name: "EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2000",
  sale: "60",
  type: "women",
},{ 
  mod: "glass",
  id: "sayed-473587433",
  img: "./image/prodcts/men/men-round-eyeglasses-2.jpg",
  name: "EyeGlasses head women`s",
  lens: "Blue-Cut",
  price: "860",
  sale: "20",
  type: "men",
},{ 
  mod: "glass",
  id: "sayed-47834783473",
  img: "./image/prodcts/men/men-round-eyeglasses-4.jpg",
  name: "EyeGlasses gold men`s metal",
  lens: "Anti-Reflective",
  price: "7000",
  sale: "60",
  type: "men",
},{ 
  mod: "glass",
  id: "sayed-4733473743",
  img: "./image/prodcts/men/men-round-eyeglasses-5.jpg",
  name: "Sunglasses white men`s metal",
  lens: "Anti-Reflective",
  price: "6000",
  sale: "80",
  type: "men",
},{
  mod: "glass",
  id: "sayed-486453",
  img: "./image/prodcts/men/men-round-eyeglasses-6.jpg",
  name: "Sunglasses red men`s",
  lens: "Anti-Reflective",
  price: "15000",
  sale: "90",
  type: "men",
},{
  mod: "glass",
  id: "sayed-345354",
  img: "./image/prodcts/men/men-round-eyeglasses-3.jpg",
  name: "Sunglasses gold men`s",
  lens: "Anti-Reflective",
  price: "500",
  sale: "20",
  type: "men",
},{
  mod: "glass",
  id: "sayed-684537",
  img: "./image/prodcts/women/women-round-eyeglasses-4.png",
  name: "Round EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2020",
  sale: "70",
  type: "women",
},{
  mod: "glass",
  id: "sayed-486486",
  img: "./image/prodcts/women/women-round-eyeglasses-5.png",
  name: "EyeGlasses women`s",
  lens: "High-Index Lenses",
  price: "20000",
  sale: "60",
  type: "women",
},{ 
  mod: "glass",
  id: "sayed-456456",
  img: "./image/prodcts/women/women-round-eyeglasses-6.png",
  name: "EyeGlasses women`s",
  lens: "High-Index Lenses",
  price: "5000",
  sale: "65",
  type: "women",
},{ 
  mod: "acc",
  id: "sayed2-312565698",
  img: "./image/accs/accs-2.jpg",
  name: "Classic Hybrid Chain",
  price: "200",
  sale: "17",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-314625698",
  img: "./image/accs/accs-1.jpg",
  name: "Men Hybrid Chain",
  price: "150",
  sale: "5",
  discr: "Men's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-45356543",
  img: "./image/accs/accs-3.jpg",
  name: "Leather glasses case",
  price: "170",
  sale: "9",
  discr: "Classic Leather glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-486356874",
  img: "./image/accs/accs-4.jpg",
  name: "Green glasses case",
  price: "100",
  sale: "12",
  discr: "Classic Leather glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-727224567",
  img: "./image/accs/accs-5.jpg",
  name: "Orange glasses case",
  price: "150",
  sale: "15",
  discr: "Orange glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-4534545634",
  img: "./image/accs/accs-6.jpg",
  name: "Classic Hybrid Chain",
  price: "250",
  sale: "3",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-544545663",
  img: "./image/accs/accs-7.jpg",
  name: "black glasses case",
  price: "550",
  sale: "55",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-453345645648",
  img: "./image/accs/accs-8.jpg",
  name: "Red glasses case",
  price: "550",
  sale: "30",
  discr: "Red glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-453446684",
  img: "./image/accs/accs-9.jpg",
  name: "Classic Hybrid Chain",
  price: "50",
  sale: "2",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-48346846443",
  img: "./image/accs/accs-11.jpg",
  name: "Classic Glasses Clener",
  price: "30",
  sale: "15",
  discr: "Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-4534866434",
  img: "./image/accs/accs-12.jpg",
  name: "Glasses Clener",
  price: "120",
  sale: "30",
  discr: "Glasses Clener Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-453448663444",
  img: "./image/accs/accs-13.jpg",
  name: "Eyeglass cleaning wipe",
  price: "15",
  sale: "5",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-79727486629",
  img: "./image/accs/accs-14.jpg",
  name: "Classic Hybrid Chain",
  price: "250",
  sale: "15",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-4524486652",
  img: "./image/accs/accs-15.jpg",
  name: "Classic Hybrid Chain",
  price: "50",
  sale: "10",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-4364664439",
  img: "./image/accs/accs-16.jpg",
  name: "Eyeglass cleaning wipe",
  price: "25",
  sale: "5",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
},{
  mod: "acc",
  id: "sayed2-3834866648",
  img: "./image/accs/accs-17.jpg",
  name: "wight glasses case",
  price: "550",
  sale: "30",
  discr: "wight glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-43964866854",
  img: "./image/accs/accs-18.jpg",
  name: "Goold Classic Hybrid Chain",
  price: "1550",
  sale: "20",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-5439738384",
  img: "./image/accs/accs-19.jpg",
  name: "Black glasses case",
  price: "550",
  sale: "30",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-287783564",
  img: "./image/accs/accs-20.jpg",
  name: "Blue glasses case",
  price: "550",
  sale: "30",
  discr: "Blue glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-7897835452",
  img: "./image/accs/accs-21.jpg",
  name: "Black glasses case",
  price: "550",
  sale: "30",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  mod: "acc",
  id: "sayed2-495278337",
  img: "./image/accs/accs-23.jpg",
  name: "Eyeglass cleaning wipe",
  price: "55",
  sale: "10",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
},{ 
  mod: "off",
  id: "sayed2-45637833456",
  img: "./image/off/off-1.jpg",
  name: "Eyeglass Warby Parker",
  price: "5500",
  sale: "10",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-45637834456",
  img: "./image/off/off-6.jpg",
  name: "Sunglasses Oakley",
  price: "2000",
  sale: "20",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-45634737485356",
  img: "./image/off/off-7.jpg",
  name: "Sunglass Ray-Ban",
  price: "10000",
  sale: "50",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-4563748373456",
  img: "./image/off/off-8.jpg",
  name: "Eyeglass Warby Gucci",
  price: "5000",
  sale: "15",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-456374373456",
  img: "./image/off/off-9.jpg",
  name: "Eyeglass Prada",
  price: "8000",
  sale: "20",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-456345743736",
  img: "./image/off/off-10.jpg",
  name: "Eyeglass Versace",
  price: "9000",
  sale: "35",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-45674373783456",
  img: "./image/off/off-11.jpg",
  name: "Eyeglass Dolce & Gabbana",
  price: "6500",
  sale: "20",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-4563733783456",
  img: "./image/off/off-12.jpg",
  name: "Eyeglass Warby Parker",
  price: "3200",
  sale: "10",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-456374333456",
  img: "./image/off/off-2.jpg",
  name: "Eyeglass Michael",
  price: "2400",
  sale: "40",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-45637343843456",
  img: "./image/off/off-3.jpg",
  name: "Eyeglass Warby Parker",
  price: "13000",
  sale: "33",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-456737433456",
  img: "./image/off/off-4.jpg",
  name: "Eyeglass Kors",
  price: "20000",
  sale: "20",
  discr: "Best quality at the lowest price",
},{ 
  mod: "off",
  id: "sayed2-4567437373456",
  img: "./image/off/off-5.jpg",
  name: "Eyeglass Coach",
  price: "35000",
  sale: "5",
  discr: "Best quality at the lowest price",
}];